fos_user:
    db_driver: orm
    user_class: App\Entity\User
    firewall_name: main
    from_email:
        address: '%env(MAILER_ADDRESS)%'
        sender_name: '%env(MAILER_SENDER_NAME)%'
    registration:
        confirmation:
            enabled: true
    service:
        mailer: fos_user.mailer.noop