integration:
    resource: "@IntegrationBundle/Controller/"
    type:     annotation
    prefix:   /

api_login_check:
    path: /api/login_check

domain:
    resource: "@DomainBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api:
    resource: '@DomainBundle/Entity/'
    type:     'api_platform'
    prefix:   '/api'
