integration:
    resource: "@IntegrationBundle/Controller/"
    type:     annotation
    prefix:   /

domain:
    resource: "@DomainBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
