gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

api_login_check:
    path: /api/login_check

integration:
    resource: "@IntegrationBundle/Controller/"
    type:     annotation
    prefix:   /

domain:
    resource: "@DomainBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api:
    resource: '@DomainBundle/Entity/'
    type:     'api_platform'
    prefix:   '/api'
