App\Entity\User:
    collectionOperations:
        get:
            method: "GET"
            access_control: "is_granted('ROLE_ADMIN')"
    itemOperations:
        get:
            method: "GET"
            access_control: "is_granted('ROLE_ADMIN') || (object !== null && user !== null && user !== 'anon.' && object.getId() === user.getId())"
