api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path:     /api/login_refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: '/user'

fos_user_reset:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: '/user/reset_password'

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: '/user'
